import type { Metadata } from "next";
import { Inter as FontSans, Outfit } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";

const font = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className={font.className}>{children}</body>
      </Provider>
    </html>
  );
}
